update_changelog:
  image: gitlab-registry.cloudandheat.com/docker/ch-chefdk-docker/image:stable
  only:
  - '/^master$/'
  script:
  - ./update_changelog
  when: always
  tags:
  - docker
  - gitlab-registry
