#!/bin/bash
set -euo pipefail
if [ ! -f CHANGELOG.new ]; then
  echo "no new changelog, nothing to do."
  exit 0
fi

if [ ! -f CHANGELOG.md ]; then
  echo "CHANGELOG.md does not exist, creating"
  printf '# Changelog\n\n' > CHANGELOG.md
fi

printf '## %s\n\n' "$(date --iso-8601=date)" >> CHANGELOG.md
cat CHANGELOG.new >> CHANGELOG.md
git rm CHANGELOG.new
git add CHANGELOG.md
git config user.email 'notifications@gitlab.cloudandheat.com'
git config user.name 'GitLab CI'
git commit -m 'Update changelog after merge automatically'
git push "https://${GITLAB_USER_NAME}:${PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" HEAD:master
